kevin-lee/maven2sbt

.gitignore, build.sbt, project/build.properties, src/main/resources/pom.xml, src/main/scala/io/kevinlee/maven2sbt/Maven2Sbt.scala
This is the first version of Maven2SBT. It still needs to handle `pom.xml` location given by the user properly.
- Create a pom.xml to build.sbt converter (#1)
=> The first version

build.sbt, project/build.properties, project/plugins.sbt
* Changed: multi-project style `build.sbt`
* Changed: scalaVersion: 2.11.7 => 2.11.12
* Changed: sbt version: 0.13.13 => 1.2.8
* Added: sbt-devoops sbt plugin
* Added: Hedgehog to libraryDependencies (no test yet)
=> Changed: config

src/main/resources/pom.xml, src/main/scala/io/kevinlee/maven2sbt/Maven2Sbt.scala
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>
<groupId>io.kevinlee</groupId>
<artifactId>j8plus</artifactId>
<version>0.0.11</version>
<packaging>jar</packaging>
<name>J8Plus</name>
<url>https://github.com/Kevin-Lee/j8plus</url>
<properties>
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
<java.version>1.8</java.version>
<junit.version>4.11</junit.version>
<test0ster1.version>0.0.6</test0ster1.version>
</properties>
<repositories>
<repository>
<id>kevin-public-releases</id>
<name>Kevin's Public Releases</name> …
```
=> Close #3 Support exclusion

build.sbt, src/main/scala/kevinlee/maven2sbt/Maven2Sbt.scala
* Changed: Package renamed from io.kevinlee => kevinlee
* Changed: minor config changes
=> Package renamed from io.kevinlee to kevinlee

src/main/scala/kevinlee/maven2sbt/Maven2Sbt.scala, src/main/scala/kevinlee/maven2sbt/Scope.scala, src/test/scala/kevinlee/maven2sbt/ScopeSpec.scala
* Added: Scope to replace maven scope
=> Scope to replace maven scope

src/main/scala/kevinlee/maven2sbt/Maven2Sbt.scala
Close #5 - Generate multi-project style build.sbt
=> Generate multi-project style build.sbt

build.sbt, project/build.properties, project/plugins.sbt
Upgraded: sbt 1.2.8 => 1.3.3 / Hedgehog and sbt-plugins
=> Upgraded: sbt 1.2.8 => 1.3.3 / Hedgehog and sbt-plugins

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/sbt-build-simple.sh, .github/workflows/sbt-build.sh
Added: GitHub Actions config and scripts
=> Added: GitHub Actions config and scripts

.github/workflows/build.yml, build.sbt
Added: Support cross Scala versions
=> Added: Support cross Scala versions

build.sbt
Added: additional project info in `build.sbt`
=> Added: additional project info in build.sbt

README.md
=> Added: GitHub Actions badges

.github/workflows/build.yml, build.sbt
Added: cache setup for GitHub Actions
=> Added: cache setup for GitHub Actions

project/build.properties
=> Upgraded: 1.3.3 => 1.3.4

build.sbt
Changed: Group ID from `kevinlee` to `io.kevinlee`
=> Changed: Group ID from kevinlee to io.kevinlee

src/main/scala/kevinlee/maven2sbt/Maven2Sbt.scala
Close #25 - Remoove hard-coded values and make them customizable
=> Close #25 - Remoove hard-coded values and make them customizable

build.sbt, project/plugins.sbt
Upgraded: sbt-devoops `1.0.2` => `11.0.3`
=> Upgraded: sbt-devoops 1.0.2 => 1.0.3

core/src/main/scala/maven2sbt/core/Common.scala, core/src/main/scala/maven2sbt/core/Dependency.scala, core/src/main/scala/maven2sbt/core/Exclusion.scala, core/src/main/scala/maven2sbt/core/Maven2Sbt.scala, core/src/main/scala/maven2sbt/core/MavenProperty.scala, core/src/main/scala/maven2sbt/core/ProjectInfo.scala, core/src/main/scala/maven2sbt/core/Repository.scala, core/src/main/scala/maven2sbt/core/Scope.scala, core/src/main/scala/maven2sbt/core/data.scala, core/src/test/scala/maven2sbt/core/CommonSpec.scala, core/src/test/scala/maven2sbt/core/DependencySpec.scala, core/src/test/scala/maven2sbt/core/ExclusionSpec.scala, core/src/test/scala/maven2sbt/core/Gens.scala, core/src/test/scala/maven2sbt/core/MavenPropertySpec.scala, core/src/test/scala/maven2sbt/core/ProjectInfoSpec.scala, core/src/test/scala/maven2sbt/core/RepositorySpec.scala, core/src/test/scala/maven2sbt/core/ScopeSpec.scala
=> Close #29 - Rename package

build.sbt, cli/src/main/scala/maven2sbt/cli/Maven2SbtApp.scala, cli/src/main/scala/maven2sbt/cli/Maven2SbtArgs.scala, project/plugins.sbt
=> Close #9 - Provide proper CLI

build.sbt
=> Upgraded: pirate

.github/workflows/build.yml, .github/workflows/release.yml, build.sbt, cli/src/main/scala/maven2sbt/cli/Maven2SbtApp.scala
Close #34 - Set up GitHub Actions to release both core lib and cli app
=> Close #34 - Set up GitHub Actions to release both core lib and cli app

.github/workflows/release.yml, build.sbt
Close #37 - Fix multiple GitHub Release issue
=> Close #37 - Fix multiple GitHub Release issue

build.sbt
Removed: Cross Scala versions from cli
=> Removed: Cross Scala versions from cli

build.sbt
Added: License for publishing to bintray
=> Added: License for publishing to bintray

build.sbt
Added: License to the core project for publishing to bintray
=> Added: License to the core project for publishing to bintray

.github/workflows/release.yml
Added: Sync to Maven Central in Release build in GitHub Actions
=> Added: Sync to Maven Central in Release build in GitHub Actions

.scripts/install.sh
Close #48 - Add installation script
=> Close #48 - Add installation script

.scripts/install.sh
Added: the default version to installation script
=> Added: the default version to installation script

.scripts/install.sh
Fixed: bug in installation script - it did not run when no version is given.
=> Fixed: bug in installation script - it did not run when no version is given

cli/src/main/scala/maven2sbt/cli/MainIO.scala, cli/src/main/scala/maven2sbt/cli/Maven2SbtApp.scala, core/src/main/scala/maven2sbt/core/Maven2Sbt.scala, core/src/main/scala/maven2sbt/core/Maven2SbtError.scala
Close #54 - Add proper error handling
=> Close #54 - Add proper error handling

core/src/main/scala/maven2sbt/core/Maven2Sbt.scala, core/src/main/scala/maven2sbt/core/Maven2SbtError.scala
Close #55 - Add build from `InputStream`
=> Close #55 - Add build from InputStream

cli/src/main/scala/maven2sbt/cli/MainIO.scala
=> Made main code clearer

cli/src/main/scala/maven2sbt/cli/Maven2SbtApp.scala, cli/src/main/scala/maven2sbt/cli/Maven2SbtArgs.scala, core/src/main/scala/maven2sbt/core/Maven2SbtError.scala
=> Close #46 - Add output file

cli/src/main/scala/maven2sbt/cli/Maven2SbtApp.scala, cli/src/main/scala/maven2sbt/cli/Maven2SbtArgs.scala
Close #53 - Add option to overwrite output file
=> Close #53 - Add option to overwrite output file

cli/src/main/scala/maven2sbt/cli/Maven2SbtApp.scala
Close #61 - Change CLI options
=> Close #61 - Change CLI options

.scripts/install.sh, README.md, build.sbt, changelogs/0.2.0.md
* Add output file (#46)
* Add installation script (#48)
* Add option to `overwrite` output file (#53)
* Add proper error handling (#54)
* Add build from `InputStream` (#55)
* Change CLI options (#61)
=> maven2sbt v0.2.0

cli/src/main/scala/maven2sbt/cli/Maven2SbtApp.scala
re-format the code and `*>` to `for-comprehension`
=> re-format the code and *> to for-comprehension

cli/src/main/scala/maven2sbt/cli/Maven2SbtApp.scala, cli/src/main/scala/maven2sbt/cli/Maven2SbtArgs.scala
Close #65 - Add subcommands to CLI for different output types
=> Close #65 - Add subcommands to CLI for different output types

.scripts/install.sh, README.md, changelogs/0.3.0.md
Add subcommands to CLI for different output types (#65)
=> maven2sbt v0.3.0

project/build.properties
=> Upgraded: sbt 1.3.4 => 1.3.5

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/task-template.md
=> Added: Issue ticket templates

build.sbt, cli/src/main/scala/maven2sbt/cli/Maven2SbtApp.scala, core/src/main/scala/maven2sbt/core/Maven2Sbt.scala
Close #72 - Use Cats and tagless-final in core
=> Close #72 - Use Cats and tagless-final in core

build.sbt
Added: `better-monadic-for` Scala compiler plugin
=> Added: better-monadic-for Scala compiler plugin

.github/workflows/build.yml, build.sbt
Close #78 - Stop supporting Scala 2.10
=> Close #78 - Stop supporting Scala 2.10

core/src/main/scala/maven2sbt/core/Maven2Sbt.scala
Close #75 - Make core's `Maven2Sbt` referentially transparent
=> Close #75 - Make core's Maven2Sbt referentially transparent

build.sbt, cli/src/main/scala/maven2sbt/cli/MainIO.scala, cli/src/main/scala/maven2sbt/cli/Maven2SbtApp.scala, core/src/main/scala/maven2sbt/core/Maven2Sbt.scala, core/src/main/scala/maven2sbt/effect/package.scala
Close #80 - Use Cats Effect in cli | 🎉 2020 🐈
=> Close #80 - Use Cats Effect in cli | 🎉 2020 🐈

cli/src/main/scala/maven2sbt/cli/MainIo.scala, cli/src/main/scala/maven2sbt/cli/Maven2SbtApp.scala
Renamed: `MainIO` `=>` `MainIo`
=> Renamed: MainIO => MainIo

.scripts/install.sh, build.sbt
Close #71 - Change the name of CLI executable to `maven2sbt`
=> Close #71 - Change the name of CLI executable to maven2sbt

project/build.properties
=> Upgraded: sbt 1.3.5 => 1.3.6

.github/workflows/build.yml
Changed: GitHub Actions - use matrix for cross Scala version build
=> Changed: GitHub Actions - use matrix for cross Scala version build

README.md
Changed: `README.md` - supported Scala version info
=> Changed: README.md - supported Scala version info

cli/src/main/scala/maven2sbt/cli/MainIo.scala, cli/src/main/scala/maven2sbt/cli/Maven2SbtApp.scala, cli/src/main/scala/maven2sbt/effect/CatsIo.scala, core/src/main/scala/maven2sbt/core/Maven2Sbt.scala, core/src/main/scala/maven2sbt/effect/Lazy.scala, core/src/main/scala/maven2sbt/effect/package.scala
Close #91 - `Maven2Sbt` is not referentially transparent
=> Close #91 - Maven2Sbt is not referentially transparent

project/build.properties
Upgraded: sbt `1.3.6` => `1.3.7`
=> Upgraded: sbt 1.3.6 => 1.3.7

build.sbt
Updated: `build.sbt` to have common sub-project config
=> Updated: build.sbt to have common sub-project config

core/src/main/scala/just/fp/Named.scala, core/src/main/scala/just/fp/Render.scala
Added: `Named` and `Render` type-classes
=> Added: Named and Render type-classes

core/src/main/scala/just/fp/Render.scala, core/src/main/scala/maven2sbt/core/BuildSbt.scala, core/src/main/scala/maven2sbt/core/Dependency.scala, core/src/main/scala/maven2sbt/core/Repository.scala, core/src/main/scala/maven2sbt/core/data.scala
Close #96 - Create `build.sbt` data
=> Close #96 - Create build.sbt data

cli/src/main/scala/maven2sbt/cli/Maven2SbtApp.scala, core/src/main/scala/maven2sbt/core/BuildSbt.scala, core/src/main/scala/maven2sbt/core/Maven2Sbt.scala
Close #95 - `Maven2Sbt` should return modeled data instead of `String`
=> Close #95 - Maven2Sbt should return modeled data instead of String

core/src/main/scala/maven2sbt/core/Maven2Sbt.scala, core/src/main/scala/maven2sbt/effect/Effects.scala
* Changed: Parametric Polymorphism => Ad hoc Polymorphism in `Effect` utils
* Added: `Effect` util to support `EitherT`
=> Polymorphism changes and EitherT support in Effect utils

core/src/main/scala/just/fp/Render.scala, core/src/main/scala/maven2sbt/core/Dependency.scala, core/src/main/scala/maven2sbt/core/Repository.scala, core/src/main/scala/maven2sbt/core/data.scala
=> Added: NamedRender[A]

project/build.properties
=> Upgrade sbt

build.sbt
Upgraded: Effectie 0.3.0 => 0.4.0
=> Upgraded: Effectie 0.3.0 => 0.4.0

cli/src/main/scala/maven2sbt/cli/Maven2SbtArgs.scala, core/src/main/scala/maven2sbt/core/BuildSbt.scala, core/src/main/scala/maven2sbt/core/Dependency.scala, core/src/main/scala/maven2sbt/core/Exclusion.scala, core/src/main/scala/maven2sbt/core/Maven2SbtError.scala, core/src/main/scala/maven2sbt/core/Repository.scala, core/src/main/scala/maven2sbt/core/Scope.scala, core/src/main/scala/maven2sbt/core/data.scala, core/src/test/resources/pom.xml, core/src/test/scala/maven2sbt/core/ExclusionSpec.scala
* Reformatting
* Another exclusion case added to an example `pom.xml`
=> Reformatting

.github/workflows/build.yml, .github/workflows/release.yml, build.sbt
Upgraded: Scala 2.12.10 => 2.12.11 / 2.13.1 => 2.13.2
=> Upgraded: Scala 2.12.10 => 2.12.11 / 2.13.1 => 2.13.2

.github/workflows/release.yml
Changed: GitHub Actions - release with different Scala and Java versions
=> Changed: GitHub Actions - release with different Scala and Java versions

.github/workflows/build.yml
Changed: GitHub Actions - build with different Java versions
=> Changed: GitHub Actions - build with different Java versions

.github/workflows/sbt-build-simple.sh, .github/workflows/sbt-build.sh, README.md
Changed: CI config to use main as the default branch
=> Changed: CI config to use main as the default branch

build.sbt, cli/src/main/scala/maven2sbt/cli/Maven2SbtApp.scala, cli/src/main/scala/maven2sbt/cli/Maven2SbtArgsParser.scala, core/src/main/scala/maven2sbt/core/Maven2Sbt.scala
Upgraded: Scala and libs
* Scala: `2.12.11` => `2.12.12`, `2.13.2` => `2.13.3`
* Cats: `2.1.0` => `2.1.1`
* Cats Effect: `2.0.0` => `2.1.4`
* Effectie: `0.4.0` => `1.0.0`
=> Upgraded: Scala and libs

.github/workflows/release.yml
=> Fixed: release.yml

.github/workflows/publish-github-pages.yml, build.sbt, project/plugins.sbt
Added: `sbt-docusaur` for publishing the doc site
=> Added: sbt-docusaur for publishing the doc site

.github/workflows/release.yml
Changed: Scala versions in CI (2.12.11 => 2.12.12 / 2.13.2 => 2.13.3)
=> Changed: Scala versions in CI (2.12.11 => 2.12.12 / 2.13.2 => 2.13.3)

build.sbt, cli/src/main/scala/maven2sbt/cli/MainIo.scala, cli/src/main/scala/maven2sbt/cli/Maven2SbtApp.scala, core/src/main/scala/maven2sbt/core/BuildSbt.scala, core/src/main/scala/maven2sbt/core/Maven2Sbt.scala
* Cats 2.1.1 => 2.2.0
* Hedgehog 64eccc9ca7dbe7a369208a14a97a25d7ccbbda67 => 0.5.1
* Effectie 1.0.0 => 1.2.0
* scala-xml 1.2.0 => 1.3.0
=> Upgraded: libs

build.sbt, core/src/main/scala/maven2sbt/core/BuildSbt.scala, core/src/main/scala/maven2sbt/core/Dependency.scala, core/src/main/scala/maven2sbt/core/MavenProperty.scala, core/src/main/scala/maven2sbt/core/Repository.scala, core/src/test/scala/maven2sbt/core/BuildSbtSpec.scala, core/src/test/scala/maven2sbt/core/DependencySpec.scala, core/src/test/scala/maven2sbt/core/MavenPropertySpec.scala, core/src/test/scala/maven2sbt/core/RepositorySpec.scala
Close #130 - Deprecate render methods no longer in use
=> Close #130 - Deprecate render methods no longer in use

website/docs/cli/get-cli.md, website/docs/library/get-library.md, website/docs/library/how-to-use.md
Updated: docs with v1.0.0 info
=> Updated: docs with v1.0.0 info

.github/workflows/build.yml
* Scala 2.12.11 => 2.12.12
* Scala 2.13.2 => 2.13.3
=> Upgraded: Scala versions in CI

.github/workflows/build.yml
Formatting changes in CI config
=> Formatting changes in CI config

.gitignore
=> Added: .bsp to .gitignore

core/src/test/resources/pom.xml
Changed: artifact IDs in `pom.xml` for testing to fake names
=> Changed: artifact IDs in pom.xml for testing to fake names

website/docs/getting-started.md, website/docusaurus.config.js, website/package-lock.json, website/package.json
Upgraded: Docusaurus `2.0.0-alpha.58` => `2.0.0-alpha.66`
=> Upgraded: Docusaurus 2.0.0-alpha.58 => 2.0.0-alpha.66

project/build.properties
=> Upgraded: sbt 1.4.1 => 1.4.3

build.sbt, core/src/main/scala/maven2sbt/core/Exclusion.scala, core/src/main/scala/maven2sbt/core/Maven2Sbt.scala, core/src/main/scala/maven2sbt/core/core.scala
Upgraded: libraries and Scala 2.13.3 => 2.13.4
=> Upgraded: libraries and Scala 2.13.3 => 2.13.4

.github/ISSUE_TEMPLATE/bug_report.md
Updated: GitHub issue ticket template for bug reporting
=> Updated: GitHub issue ticket template for bug reporting

core/src/main/scala/maven2sbt/core/Dependency.scala, core/src/main/scala/maven2sbt/core/MavenProperty.scala, core/src/main/scala/maven2sbt/core/Repository.scala
=> Removed: unused methods

core/src/test/scala/maven2sbt/core/BuildSbtSpec.scala
=> Fix #148 - Added more tests

project/build.properties
=> Upgraded: sbt 1.4.3 => 1.4.5

core/src/main/scala/maven2sbt/core/BuildSbt.scala, core/src/main/scala/maven2sbt/core/Dependency.scala, core/src/main/scala/maven2sbt/core/Exclusion.scala, core/src/main/scala/maven2sbt/core/MavenProperty.scala, core/src/main/scala/maven2sbt/core/Props.scala, core/src/main/scala/maven2sbt/core/StringUtils.scala, core/src/test/scala/maven2sbt/core/CommonSpec.scala
=> Issue #149 - clean up

core/src/main/scala/maven2sbt/core/BuildSbt.scala, core/src/main/scala/maven2sbt/core/Dependency.scala, core/src/main/scala/maven2sbt/core/Exclusion.scala, core/src/main/scala/maven2sbt/core/MavenProperty.scala, core/src/main/scala/maven2sbt/core/Props.scala, core/src/main/scala/maven2sbt/core/StringUtils.scala, core/src/test/scala/maven2sbt/core/StringUtilsSpec.scala
=> Issue #149 - clean up: naming

core/src/test/scala/maven2sbt/core/StringUtilsSpec.scala
Issue #149 - clean up: names in tests
=> Issue #149 - clean up: names in tests

core/src/main/scala/maven2sbt/core/RenderedString.scala, core/src/main/scala/maven2sbt/core/StringUtils.scala, core/src/test/scala/maven2sbt/core/Gens.scala, core/src/test/scala/maven2sbt/core/PropSpec.scala, core/src/test/scala/maven2sbt/core/PropsSpec.scala, core/src/test/scala/maven2sbt/core/StringUtilsSpec.scala, core/src/test/scala/maven2sbt/core/TestUtils.scala
Issue #149 - Added functions to render `String` with props
=> Issue #149 - Added functions to render String with props

core/src/main/scala/maven2sbt/core/StringUtils.scala, core/src/test/scala/maven2sbt/core/Gens.scala
Fix #168 - String interpolation is broken
=> Fix #168 - String interpolation is broken

core/src/main/scala/just/fp/Render.scala, core/src/main/scala/maven2sbt/core/BuildSbt.scala, core/src/main/scala/maven2sbt/core/Dependency.scala, core/src/main/scala/maven2sbt/core/Exclusion.scala, core/src/main/scala/maven2sbt/core/Maven2Sbt.scala, core/src/main/scala/maven2sbt/core/Props.scala, core/src/main/scala/maven2sbt/core/RenderedString.scala, core/src/main/scala/maven2sbt/core/Repository.scala, core/src/main/scala/maven2sbt/core/StringUtils.scala, core/src/main/scala/maven2sbt/core/core.scala, core/src/test/resources/pom.xml, core/src/test/scala/maven2sbt/core/BuildSbtSpec.scala, core/src/test/scala/maven2sbt/core/DependencySpec.scala, core/src/test/scala/maven2sbt/core/ExclusionSpec.scala, core/src/test/scala/maven2sbt/core/Gens.scala, core/src/test/scala/maven2sbt/core/PropSpec.scala, core/src/test/scala/maven2sbt/core/PropsSpec.scala, core/src/test/scala/maven2sbt/core/RepositorySpec.scala
Fix #170 - Some String values are not rendered with props properly
=> Fix #170 - Some String values are not rendered with props properly

.scripts/install.sh
Updated: The installation script with v1.1.0
=> Updated: The installation script with v1.1.0

website/docs/cli/how-to-use.md, website/docs/library/get-library.md
=> Updated: docs

cli/src/main/scala/maven2sbt/cli/Maven2SbtArgsParser.scala
Close #175 - Add missing info in `--props-name`
=> Close #175 - Add missing info in --props-name

website/docs/cli/get-cli.md
Updated: docs with the new binary file paths
=> Updated: docs with the new binary file paths

website/docs/library/how-to-use.md
Updated: docs with the new argument info when it's used as a library (the core project)
=> Updated: docs with the new argument info when it's used as a library (the core project)

cli/src/main/scala/maven2sbt/cli/Maven2SbtArgsParser.scala
Removed: duplicate code in `Maven2SbtArgsParser`
=> Removed: duplicate code in Maven2SbtArgsParser

changelogs/1.1.1.md, project/SbtProjectInfo.scala
* Add missing info in `--props-name` (#175)
=> maven2sbt v1.1.1

.scripts/install.sh
Updated: The installation script with v1.1.1
=> Updated: The installation script with v1.1.1

website/docs/cli/get-cli.md, website/docs/library/get-library.md
Updated: docs with the new version info (v1.1.1)
=> Updated: docs with the new version info (v1.1.1)

project/build.properties
=> Upgraded: sbt 1.4.5 => 1.4.6

cli/src/main/scala/maven2sbt/cli/Maven2SbtApp.scala, core/src/main/scala/maven2sbt/core/BuildSbt.scala, core/src/main/scala/maven2sbt/core/Dependency.scala, core/src/main/scala/maven2sbt/core/Libs.scala, core/src/main/scala/maven2sbt/core/Maven2Sbt.scala, core/src/test/scala/maven2sbt/core/Gens.scala, core/src/test/scala/maven2sbt/core/LibsSpec.scala
Close #185 - Add support Maven's `<dependencyManagement>`
=> Close #185 - Add support Maven's dependencyManagement

project/build.properties
=> Upgraded: sbt 1.4.6 => 1.4.7

build.sbt, project/plugins.sbt
Upgraded: libraries and sbt plugins
=> Upgraded: libraries and sbt plugins

cli/src/main/scala/maven2sbt/cli/Maven2SbtApp.scala, core/src/main/scala/maven2sbt/core/Dependency.scala, core/src/main/scala/maven2sbt/core/Libs.scala, core/src/main/scala/maven2sbt/core/Maven2Sbt.scala, core/src/main/scala/maven2sbt/core/core.scala, core/src/test/scala/maven2sbt/core/DependencySpec.scala, core/src/test/scala/maven2sbt/core/Gens.scala, core/src/test/scala/maven2sbt/core/LibsSpec.scala
Close #187 - Support Scala dependency with `scalaBinaryVersion`
=> Close #187 - Support Scala dependency with scalaBinaryVersion

core/src/main/scala/maven2sbt/core/BuildSbt.scala, core/src/main/scala/maven2sbt/core/Dependency.scala, core/src/main/scala/maven2sbt/core/Exclusion.scala, core/src/main/scala/maven2sbt/core/Props.scala, core/src/main/scala/maven2sbt/core/Render.scala, core/src/main/scala/maven2sbt/core/Repository.scala, core/src/main/scala/maven2sbt/core/core.scala
Moved: `Render` from `just.fp` to `maven2sbt.core`
=> Moved: Render from just.fp to maven2sbt.core

.github/workflows/build.yml, core/src/main/scala/maven2sbt/core/BuildSbt.scala, core/src/main/scala/maven2sbt/core/Dependency.scala, core/src/main/scala/maven2sbt/core/Exclusion.scala, core/src/main/scala/maven2sbt/core/Libs.scala, core/src/main/scala/maven2sbt/core/ReferencedRender.scala, core/src/main/scala/maven2sbt/core/Scope.scala, core/src/main/scala/maven2sbt/core/StringUtils.scala, core/src/main/scala/maven2sbt/core/core.scala, core/src/test/scala/maven2sbt/core/BuildSbtSpec.scala, core/src/test/scala/maven2sbt/core/DependencySpec.scala, core/src/test/scala/maven2sbt/core/Gens.scala, core/src/test/scala/maven2sbt/core/LibsSpec.scala, core/src/test/scala/maven2sbt/core/ScopeSpec.scala
Close #190 - Use `libs` for `libraryDependencies` when it's found in `libs`
=> Close #190 - Use libs for libraryDependencies when it's found in libs

cli/src/main/scala/maven2sbt/cli/Maven2SbtApp.scala, cli/src/main/scala/maven2sbt/cli/Maven2SbtArgs.scala, cli/src/main/scala/maven2sbt/cli/Maven2SbtArgsParser.scala, core/src/main/scala/maven2sbt/core/BuildSbt.scala, core/src/main/scala/maven2sbt/core/Dependency.scala, core/src/main/scala/maven2sbt/core/ReferencedRender.scala, core/src/test/scala/maven2sbt/core/BuildSbtSpec.scala, core/src/test/scala/maven2sbt/core/DependencySpec.scala, core/src/test/scala/maven2sbt/core/Gens.scala
Close #191 - Add libs name param (`--libs-name`)
=> Close #191 - Add libs name param (--libs-name)

cli/src/main/scala/maven2sbt/cli/Maven2SbtApp.scala, cli/src/main/scala/maven2sbt/cli/Maven2SbtArgs.scala, cli/src/main/scala/maven2sbt/cli/Maven2SbtArgsParser.scala
Close #192 - Add Scala binary version param (`--scala-binary-version-name`)
=> Close #192 - Add Scala binary version param (--scala-binary-version-name)

.github/workflows/build.yml, .github/workflows/sbt-build-all.sh, build.sbt
Updated: GitHub Actions build config
=> Updated: GitHub Actions build config

.github/workflows/release.yml, .github/workflows/sbt-release.sh
Updated: GitHub Actions release config
=> Updated: GitHub Actions release config

.github/workflows/sbt-release.sh
=> Fixed: The release script

.github/workflows/manual-github-upload-artifacts-all.yml, .github/workflows/sbt-github-upload-artifacts.sh
Added: manual upload artifacts to GitHub Release
=> Added: manual upload artifacts to GitHub Release

website/docs/library/how-to-use.md
Updated: docs with the missing param
=> Updated: docs with the missing param

website/docs/cli/get-cli.md
Updated: docs - the supported Java version
=> Updated: docs - the supported Java version

.github/workflows/doc-site-build-only.yml
Add: GitHub Actions for building the doc site without publishing it
=> Add: GitHub Actions for building the doc site without publishing it

.github/workflows/manual-maven-sync.yml, .github/workflows/manual-publish.yml, .github/workflows/sbt-publish-only.sh, .github/workflows/sbt-release.sh
Added: GitHub Actions - Manual builds
=> Added: GitHub Actions - Manual builds

.github/workflows/manual-maven-sync.yml, .github/workflows/manual-publish.yml
Changed: GitHub Actions - workflow names
=> Changed: GitHub Actions - workflow names

.github/workflows/manual-maven-sync.yml, build.sbt, project/plugins.sbt
* Upgraded: Scala `2.13.3` => `2.13.5` / sbt plugins
* Updated: config
=> Upgraded: Scala 2.13.3 => 2.13.5 / sbt plugins

build.sbt, cli/src/graal/reflect-config.json
Issue #214 - Add config for building maven2sbt with GraalVM Native Image
=> Issue #214 - Add config for building maven2sbt with GraalVM Native Image

.github/workflows/build.yml, build.sbt, sbt
Close #214 - Build with GraalVM - GitHub Actions to generate binary for macOS and Linux
**GraalVM build for Windows has been disabled for now since it keeps failing.**
=> Close #214 - Build with GraalVM - GitHub Actions to generate binary for macOS and Linux

build.sbt, project/plugins.sbt
Upgraded: sbt-devoops `2.0.0` => `2.1.0`
=> Upgraded: sbt-devoops 2.0.0 => 2.1.0

.github/workflows/build.yml, .github/workflows/manual-github-upload-artifacts-all.yml, .github/workflows/manual-github-upload-graalvm-native-image.yml, .github/workflows/manual-maven-sync.yml, .github/workflows/manual-publish.yml, .github/workflows/release.yml, build.sbt
Close #218 - Release GraalVM Native Image for macOS and Linux
=> Close #218 - Release GraalVM Native Image for macOS and Linux

.github/workflows/build.yml
Disable build for PR since every push builds
=> Disable build for PR since every push builds

.scripts/install-graal-macos.sh
Close #223 - Add installation script for GraalVM Native Image for macOS
=> Close #223 - Add installation script for GraalVM Native Image for macOS

.scripts/install-graal-ubuntu.sh
Close #225 - Add installation script for GraalVM Native Image for Ubuntu and Debian Linux
=> Close #225 - Add installation script for GraalVM Native Image for Ubuntu and Debian Linux

.github/workflows/build.yml, .github/workflows/release.yml, build.sbt, cli/src/graal/reflect-config.json, project/plugins.sbt
Close #227 - Change GitHub Actions for better GraalVM support
=> Close #227 - Change GitHub Actions for better GraalVM support

.github/workflows/build.yml, .github/workflows/manual-github-upload-graalvm-native-image.yml, .github/workflows/release.yml, build.sbt
Close #229 - Add GraalVM Native Image build for Windows
=> Close #229 - Add GraalVM Native Image build for Windows

build.sbt
Close #229 - Fixed: GraalVM Native Image binary file location
=> Close #229 - Fixed: GraalVM Native Image binary file location

.github/workflows/manual-github-upload-graalvm-native-image.yml, .github/workflows/release.yml
Close #229 - Fixed: Missing GitHub token setup
=> Close #229 - Fixed: Missing GitHub token setup

website/docs/cli/get-cli.md
Updated: Doc - How to install GraalVM Native Image versions
=> Updated: Doc - How to install GraalVM Native Image versions

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/sbt-build-all.sh, .github/workflows/sbt-github-upload-artifacts.sh, .github/workflows/sbt-release.sh, build.sbt
Close #240 - Stop uploading the jar files, the Debian package and the tarball file to GitHub Release
=> Close #240 - Stop uploading the jar files, the Debian package and the tarball file to GitHub Release

.github/workflows/sbt-build-all.sh, .github/workflows/sbt-github-upload-artifacts.sh, .github/workflows/sbt-release.sh
Close #240 - Fix build scripts
=> Close #240 - Fix build scripts

.github/workflows/sbt-github-upload-artifacts.sh, .github/workflows/sbt-release.sh
=> Fixed: Build scripts

.scripts/install-graal-macos.sh, .scripts/install-graal-ubuntu.sh, .scripts/install.sh
Updated: The installation scripts
=> Updated: The installation scripts

build.sbt
Updated: Config - It always uses the latest pirate.
=> Updated: Config - It always uses the latest pirate.

.github/workflows/build.yml, .github/workflows/release.yml, build.sbt, project/build.properties, project/plugins.sbt
Close #249 - Support Scala `3.0.0-RC2` and Scala `3.0.0-RC3`
=> Close #249 - Support Scala 3.0.0-RC2 and Scala 3.0.0-RC3

.github/workflows/build-graal.yml, .github/workflows/build.yml, .github/workflows/release.yml
=> Updated: GitHub Actions

build.sbt
Updated: `build.sbt` - clean up
=> Updated: build.sbt - clean up

.github/workflows/doc-site-build-only.yml, .github/workflows/doc-site-publish.yml, website/package-lock.json, website/package.json
Upgraded: `Docusaurus` and `docusaurus-lunr-search`
=> Upgraded: Docusaurus and docusaurus-lunr-search

sbt
=> Upgraded: the sbt script

README.md, website/docs/getting-started.md
Upgraded: docs - minor changes in `README.md` and `getting-started.md`
=> Upgraded: docs - minor changes in README.md and getting-started.md

.github/workflows/build-graal.yml, .github/workflows/release.yml
=> Upgraded: GraalVM build

project/build.properties
Upgraded: sbt `1.5.1` => `1.5.3`
=> Upgraded: sbt 1.5.1 => 1.5.3

.github/workflows/release.yml
Fixed: GitHub Actions config for release
=> Fixed: GitHub Actions config for release

.scripts/install-graal-macos.sh, .scripts/install-graal-ubuntu.sh, .scripts/install.sh
Updated: The installation scripts with `v1.4.0` info
=> Updated: The installation scripts with v1.4.0 info

project/plugins.sbt
Upgraded: `sbt-devoops` to `2.6.0`
=> Upgraded: sbt-devoops

build.sbt
=> Removed: unused libraries

core/src/main/scala-3/maven2sbt/core/Libs.scala, core/src/main/scala-3/maven2sbt/core/MavenProperty.scala, core/src/main/scala-3/maven2sbt/core/Props.scala, core/src/main/scala-3/maven2sbt/core/Repository.scala, core/src/main/scala-3/maven2sbt/core/core.scala
=> Improved: use of opaque types

build.sbt, core/src/main/scala/maven2sbt/core/Maven2Sbt.scala
Close #275 - Upgrade Scala 3 to `3.0.1` and Effectie to `1.14.0`
=> Close #275 - Upgrade Scala 3 to 3.0.1 and Effectie to 1.14.0

build.sbt, cli/src/main/scala/maven2sbt/cli/Maven2SbtApp.scala, core/src/main/scala/maven2sbt/core/Maven2Sbt.scala
Close #277 - Use `extras-cats`
=> Close #277 - Use extras-cats

build.sbt, project/plugins.sbt
Upgraded: sbt-docusaur `0.5.0` => `0.6.0`
=> Upgraded: sbt-docusaur 0.5.0 => 0.6.0

.scripts/install-graal-macos.sh, .scripts/install-graal-ubuntu.sh, .scripts/install.sh, website/docs/cli/get-cli.md
Updated: The installation scripts and docs with more convenient `PATH` setup
=> Updated: The installation scripts and docs with more convenient PATH setup

project/plugins.sbt
Upgraded: sbt plugins
* sbt-devoops `2.6.0` => `2.11.0`
* sbt-docusaur `0.6.0` => `0.8.0`
=> Upgraded: sbt plugins

website/docusaurus.config.js, website/package-lock.json, website/package.json, website/src/css/custom.css
=> Upgraded: Docusaurus

core/src/main/scala/maven2sbt/core/BuildSbt.scala
Close #285 - Make `GlobalSettings.empty` constant
=> Close #285 - Make GlobalSettings.empty constant

build.sbt
=> Update: pirate project info

core/src/test/scala/maven2sbt/core/StringUtilsSpec.scala, project/build.properties
Upgrade: sbt `1.5.5` => `1.6.2`
=> Upgrade: sbt 1.5.5 => 1.6.2

build.sbt
=> Fix: pirate sub-project name

project/plugins.sbt
Upgrade: `sbt-devoops` `2.11.0` => `2.16.0` / `sbt-docusaur` `0.8.0` => `0.9.0`
=> Upgrade: sbt-devoops 2.11.0 => 2.16.0 / sbt-docusaur 0.8.0 => 0.9.0

.github/workflows/build-graal.yml, .github/workflows/build.yml, .github/workflows/doc-site-build-only.yml, .github/workflows/doc-site-publish.yml, build.sbt
Upgrade Scala `3.0.1` => `3.1.2` and libraries
=> Upgrade Scala `3.0.1` => `3.1.2` and libraries

.github/workflows/release.yml, build.sbt, modules/maven2sbt-core/src/main/scala-3/maven2sbt/core/Repository.scala, modules/maven2sbt-core/src/main/scala-3/maven2sbt/core/core.scala, modules/maven2sbt-core/src/test/scala/maven2sbt/core/DependencySpec.scala, project/SbtProjectInfo.scala, project/plugins.sbt
Close #294 - Set up `WartRemover` for Scala 3
=> Close #294 - Set up WartRemover for Scala 3

project/SbtProjectInfo.scala, project/plugins.sbt
Close #294 - Upgrade WartRemover to `3.0.2`
=> Close #294 - Upgrade WartRemover to 3.0.2

project/build.properties
Upgrade sbt `1.6.2` => `1.7.1`
=> Upgrade sbt `1.6.2` => `1.7.1`

sbt
Close #304 - Upgrade sbt-extras script
=> Close #304 - Upgrade sbt-extras script

.github/workflows/build.yml, .github/workflows/doc-site-build-only.yml, .github/workflows/doc-site-publish.yml, build.sbt, modules/maven2sbt-cli/src/main/scala/maven2sbt/cli/MainIo.scala, modules/maven2sbt-cli/src/main/scala/maven2sbt/cli/Maven2SbtApp.scala, modules/maven2sbt-cli/src/main/scala/maven2sbt/cli/Maven2SbtArgsParser.scala, modules/maven2sbt-core/src/main/scala-2.12_2.13/maven2sbt/core/Repository.scala, modules/maven2sbt-core/src/main/scala-2.12_2.13/maven2sbt/core/core.scala, modules/maven2sbt-core/src/main/scala/maven2sbt/core/BuildSbt.scala, modules/maven2sbt-core/src/main/scala/maven2sbt/core/DependencyPlus.scala, modules/maven2sbt-core/src/main/scala/maven2sbt/core/Exclusion.scala, modules/maven2sbt-core/src/main/scala/maven2sbt/core/LibsPlus.scala, modules/maven2sbt-core/src/main/scala/maven2sbt/core/Maven2Sbt.scala, modules/maven2sbt-core/src/test/scala/maven2sbt/core/BuildSbtSpec.scala, modules/maven2sbt-core/src/test/scala/maven2sbt/core/DependencySpec.scala, modules/maven2sbt-core/src/test/scala/maven2sbt/core/ExclusionSpec.scala, modules/maven2sbt-core/src/test/scala/maven2sbt/core/Gens.scala, modules/maven2sbt-core/src/test/scala/maven2sbt/core/LibsSpec.scala, modules/maven2sbt-core/src/test/scala/maven2sbt/core/MavenPropertySpec.scala, modules/maven2sbt-core/src/test/scala/maven2sbt/core/ProjectInfoSpec.scala, modules/maven2sbt-core/src/test/scala/maven2sbt/core/PropSpec.scala, modules/maven2sbt-core/src/test/scala/maven2sbt/core/PropsSpec.scala, modules/maven2sbt-core/src/test/scala/maven2sbt/core/RepositorySpec.scala, modules/maven2sbt-core/src/test/scala/maven2sbt/core/ScopeSpec.scala, modules/maven2sbt-core/src/test/scala/maven2sbt/core/StringUtilsSpec.scala, modules/maven2sbt-core/src/test/scala/maven2sbt/core/TestUtils.scala, project/plugins.sbt
Close #311 - Bump Scala 2 and libraries
* 2.12.14 => 2.12.17
* 2.13.6 => 2.13.10
* Bump libraries and sbt plugins
=> Close #311 - Bump Scala 2 and libraries

.github/workflows/sbt-build-all.sh, project/build.properties, project/plugins.sbt
Bump sbt and sbt plugins
- sbt 1.7.1 => 1.8.0
- sbt-scoverage 1.6.1 => 2.0.6
- sbt-coveralls 1.2.7 => 1.3.5
- sbt-native-packager 1.8.1 => 1.9.11
- sbt-wartremover 3.0.6 => 3.0.7
- sbt-devoops 2.23.0 => 2.24.0
- sbt-docusaur 0.12.0 => 0.13.0
=> Bump sbt and sbt plugins

.github/workflows/build.yml
=> Add: GitHub Actions - Codecov

build.sbt
Close #316 - Upgrade GraalVM to 22.3.0
=> Close #316 - Upgrade GraalVM to 22.3.0

.scalafmt.conf, build.sbt
Update `build.sbt` and `.scalafmt.conf`
=> Update build.sbt and .scalafmt.conf

modules/maven2sbt-core/src/main/scala/maven2sbt/core/Maven2Sbt.scala
=> Use more Scala 3 syntax

project/plugins.sbt
Add: `sbt-devoops-starter` (`2.24.0`)
=> Add: sbt-devoops-starter (2.24.0)

build.sbt, modules/maven2sbt-cli/src/main/scala/maven2sbt/cli/Maven2SbtApp.scala, modules/maven2sbt-core/src/main/scala/maven2sbt/core/Maven2Sbt.scala, modules/maven2sbt-core/src/main/scala/maven2sbt/core/StringUtils.scala, modules/maven2sbt-core/src/test/scala/maven2sbt/core/DependencySpec.scala, modules/maven2sbt-core/src/test/scala/maven2sbt/core/PropSpec.scala, project/plugins.sbt
Add: sbt-tpolecat (0.4.1) and update the code accordingly
=> Add: sbt-tpolecat (0.4.1) and update the code accordingly

.scalafix-scala2.conf, .scalafix-scala3.conf, build.sbt, modules/maven2sbt-core/src/main/scala-2.12_2.13/maven2sbt/core/Repository.scala, modules/maven2sbt-core/src/main/scala-2.12_2.13/maven2sbt/core/core.scala, modules/maven2sbt-core/src/main/scala/maven2sbt/core/Dependency.scala, modules/maven2sbt-core/src/main/scala/maven2sbt/core/DependencyPlus.scala, modules/maven2sbt-core/src/main/scala/maven2sbt/core/Exclusion.scala, modules/maven2sbt-core/src/main/scala/maven2sbt/core/LibsPlus.scala, modules/maven2sbt-core/src/main/scala/maven2sbt/core/ProjectInfo.scala, modules/maven2sbt-core/src/main/scala/maven2sbt/core/Prop.scala, modules/maven2sbt-core/src/main/scala/maven2sbt/core/RepositoryPlus.scala, modules/maven2sbt-core/src/main/scala/maven2sbt/core/Scope.scala, modules/maven2sbt-core/src/test/scala/maven2sbt/core/MavenPropertySpec.scala, modules/maven2sbt-core/src/test/scala/maven2sbt/core/TestUtils.scala
Add: `sbt-scalafix` and update the code accordingly
=> Add: sbt-scalafix and update the code accordingly

modules/maven2sbt-core/src/main/scala/maven2sbt/core/DependencyPlus.scala, modules/maven2sbt-core/src/main/scala/maven2sbt/core/Exclusion.scala, modules/maven2sbt-core/src/test/scala/maven2sbt/core/DependencySpec.scala, modules/maven2sbt-core/src/test/scala/maven2sbt/core/ExclusionSpec.scala, modules/maven2sbt-core/src/test/scala/maven2sbt/core/Gens.scala, modules/maven2sbt-core/src/test/scala/maven2sbt/core/LibsSpec.scala
Close #327 - Exclude should not have Scala binary version suffix
=> Close #327 - Exclude should not have Scala binary version suffix

build.sbt
Close #332 - Upgrade libraries
* cats-effect to `3.4.7`
* effectie to `2.0.0-beta6`
* logger-f to `2.0.0-beta9`
* extras to `0.31.0`
=> Close #332 - Upgrade libraries

.github/workflows/build-graal.yml, .github/workflows/build.yml, .github/workflows/release.yml, build.sbt, project/plugins.sbt
Bump Scala 3: `3.2.1` => `3.2.2`
=> Bump Scala 3: `3.2.1` => `3.2.2`

project/build.properties
=> Bump sbt 1.8.0 => 1.8.3

website/docs/cli/get-cli.md, website/docs/getting-started.md, website/docs/library/get-library.md
Update: docs with the latest version info (`1.5.0`)
=> Update: docs with the latest version info (`1.5.0`)

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/task-template.md, README.md, build.sbt, changelogs/0.1.0.md, changelogs/0.2.0.md, changelogs/0.3.0.md, changelogs/0.4.0.md, changelogs/1.0.0.md, changelogs/1.1.0.md, changelogs/1.1.1.md, changelogs/1.2.0.md, changelogs/1.3.0.md, changelogs/1.4.0.md, modules/maven2sbt-core/src/test/resources/pom.xml, website/docs/getting-started.md, website/docusaurus.config.js
Update pirate to the latest and update GitHub username (`Kevin-Lee` => `kevin-lee`)
=> Update pirate to the latest and update GitHub username (Kevin-Lee => kevin-lee)

project/build.properties
=> Bump sbt to `1.9.2`

build.sbt, modules/maven2sbt-core/src/main/scala-3/maven2sbt/core/Libs.scala, modules/maven2sbt-core/src/main/scala-3/maven2sbt/core/MavenProperty.scala, modules/maven2sbt-core/src/main/scala-3/maven2sbt/core/Props.scala, modules/maven2sbt-core/src/main/scala-3/maven2sbt/core/Repository.scala, modules/maven2sbt-core/src/main/scala-3/maven2sbt/core/data.scala
Close #354 - Replace `opaque type`s (newtypes) with `refined4s`
=> Close #354 - Replace `opaque type`s (newtypes) with `refined4s`

build.sbt
Bump `effectie` and `logger-f`
- `effectie` to `2.0.0-beta14`
- `logger-f` to `2.0.0-beta24`
=> Bump effectie and logger-f

.github/workflows/doc-site-build-only.yml, .github/workflows/doc-site-publish.yml
=> Fix broken docs build

.github/workflows/build-graal.yml, .github/workflows/release.yml, .scripts/install-graal-macos.sh, .scripts/install-graal-ubuntu.sh, .scripts/install.sh, build.sbt
Close #360 - Release for multiple macOS versions including 13 (Intel), 14 (Apple Silicon) and 15 (Apple Silicon)
=> Close #360 - Release for multiple macOS versions including 13 (Intel), 14 (Apple Silicon) and 15 (Apple Silicon)

.github/workflows/build-graal.yml, .github/workflows/build.yml, .github/workflows/doc-site-build-only.yml, .github/workflows/doc-site-publish.yml, .github/workflows/release.yml
Update GitHub Actions settings - Upgrade actions/cache from v2 to v4 in workflow files
=> Update GitHub Actions settings - Upgrade actions/cache from v2 to v4 in workflow files

.github/workflows/build-graal.yml, .github/workflows/build.yml, .github/workflows/doc-site-build-only.yml, .github/workflows/doc-site-publish.yml, .github/workflows/release.yml
Update build configurations to use `actions/setup-java` and `sbt/setup-sbt`
=> Update build configurations to use `actions/setup-java` and `sbt/setup-sbt`

README.md, website/docs/getting-started.md, website/src/pages/index.js
* Update hit counter badge URL in documentation
* Update hit counter badge URL in `README.md`
=> Update hit counter badge

build.sbt
Upgraded Cats to 2.13.0 and Cats Effect to 3.6.1.
=> Upgraded Cats to 2.13.0 and Cats Effect to 3.6.1

.github/workflows/release.yml
Update: `release.yml` - Fix Java version and distribution
=> Update: `release.yml` - Fix Java version and distribution

project/plugins.sbt
`plugins.sbt`: Upgrade `sbt-ci-release` to `1.11.1`
=> `plugins.sbt`: Upgrade `sbt-ci-release` to `1.11.1`

build.sbt
Update `build.sbt`: Remove unnecessary config
=> Update `build.sbt`: Remove unnecessary config

project/build.properties
=> Bump sbt to 1.11.2

.github/workflows/build-graal.yml, .github/workflows/release.yml
Update GitHub Actions workflows
=> Update GitHub Actions workflows
