- src/main/scala/io/kevinlee/maven2sbt/Maven2Sbt.scala
From
```sbt
resolvers ++= Seq(
"Kevin's Public Releases" at "http://dl.bintray.com/kevinlee/maven",
"Kevin's Public Releases 2" at "http://blah.blah.blah/maven"
)
libraryDependencies ++= Seq(
"junit" % "junit" % junitVersion % "test",
"io.kevinlee" % "test0ster1" % test0ster1Version % "test",
"io.kevinlee" % "nothing" % "0.0.1",
"org.assertj" % "assertj-core" % "1.5.0" % "test",
"org.mockito" % "mockito-all" % "1.9.5" % "test"
)
```
To
```sbt
resolvers ++= Seq(
"Kevin's Public Releases" at "http://dl.bintray.com/kevinlee/maven"
, "Kevin's Public Releases 2" at "http://blah.blah.blah/maven"
)
libraryDependencies ++= Seq(
"junit" % "junit" % junitVersion % "test"
, "io.kevinlee" % "test0ster1" % test0ster1Version % "test"
, "io.kevinlee" % "nothing" % "0.0.1"
, "org.assertj" % …
```
> Changed: Formatting of the build.sbt generated by maven2sbt

- build.sbt
- changelogs/0.1.0.md
* Create a `pom.xml` to `build.sbt` converter (#1)
* Support exclusion (#3)
* Clean up the code (#4)
* Generate multi-project style `build.sbt` (#5)
* Provide proper CLI (#9)
* Remove hard-coded values and make them customizable (#25)
* Create sub-projects for core and CLI (#27)
* Rename package (#29)
* Set up GitHub Actions to release both `core` lib and `cli` app (#34)
* Fix multiple GitHub Release issue (#37)
> maven2sbt v0.1.0

- README.md
Updated: `README.md` - easier ways to install `maven2sbt-cli`
> Updated: README.md - easier ways to install maven2sbt-cli

- .scripts/install.sh
- README.md
- build.sbt
- changelogs/0.4.0.md
* Change the name of CLI executable to maven2sbt (#71)
* Use Cats and Tagless-final in core (#72)
* Make core's Maven2Sbt referentially transparent (#75)
* Stop supporting Scala 2.10 (#78)
* Use Cats Effect in cli (#80)
> maven2sbt v0.4.0

- build.sbt
Removed: The `context-applied` compiler plugin as IntelliJ IDEA does not work well with it.
> Removed: The context-applied compiler plugin

- core/src/main/scala/maven2sbt/core/Dependency.scala
- core/src/main/scala/maven2sbt/core/Exclusion.scala
- core/src/main/scala/maven2sbt/core/MavenProperty.scala
Fix #126 - Variables from maven properties are double-quoted
> Fix #126 - Variables from maven properties are double-quoted

- core/src/main/scala/maven2sbt/core/BuildSbt.scala
- core/src/main/scala/maven2sbt/core/Common.scala
- core/src/main/scala/maven2sbt/core/MavenProperty.scala
- core/src/test/resources/pom.xml
- core/src/test/scala/maven2sbt/core/CommonSpec.scala
- core/src/test/scala/maven2sbt/core/Gens.scala
- core/src/test/scala/maven2sbt/core/MavenPropertySpec.scala
Fix #125 - Maven property name with hyphens is not converted to Scala variable name properly
> Fix #125 - Maven property name with hyphens is not converted to Scala variable name properly

- .scripts/install.sh
- build.sbt
- changelogs/1.0.0.md
- project/plugins.sbt
* Use newtype instead of value class (#132)
* Deprecate render methods no longer in use (#130)
* Use Effectie (#108)
* Maven2Sbt should return modeled data instead of `String` (#95)
* Variables from maven properties are double-quoted (#126)
* Maven property name with hyphens is not converted to Scala variable name properly (#125)
* Maven2Sbt is not referentially transparent (#91)
> maven2sbt v1.0.0

- core/src/main/scala/maven2sbt/core/BuildSbt.scala
- core/src/main/scala/maven2sbt/core/Dependency.scala
- core/src/main/scala/maven2sbt/core/Exclusion.scala
- core/src/main/scala/maven2sbt/core/Maven2Sbt.scala
- core/src/main/scala/maven2sbt/core/MavenProperty.scala
- core/src/main/scala/maven2sbt/core/Props.scala
- core/src/test/scala/maven2sbt/core/BuildSbtSpec.scala
- core/src/test/scala/maven2sbt/core/DependencySpec.scala
- core/src/test/scala/maven2sbt/core/ExclusionSpec.scala
- core/src/test/scala/maven2sbt/core/PropSpec.scala
- core/src/test/scala/maven2sbt/core/PropsSpec.scala
Fix #147 - possible reserved sbt words used as property names (e.g. `scalaVersion`, `version`, etc.)
> Fix #147 - possible reserved sbt words used as property names (e.g. scalaVersion, version, etc.)

- core/src/main/scala/maven2sbt/core/Exclusion.scala
- core/src/test/scala/maven2sbt/core/ExclusionSpec.scala
Fix #158 - The wrong named parameter (i.e. `artifact`) was used in `ExclusionRule` - replaced with `name`
> Fix #158 - The wrong named parameter (i.e. artifact) was used in ExclusionRule - replaced with name

- core/src/main/scala/maven2sbt/core/BuildSbt.scala
- core/src/main/scala/maven2sbt/core/Exclusion.scala
- core/src/main/scala/maven2sbt/core/Props.scala
- core/src/main/scala/maven2sbt/core/core.scala
- core/src/test/scala/maven2sbt/core/BuildSbtSpec.scala
- core/src/test/scala/maven2sbt/core/ExclusionSpec.scala
- core/src/test/scala/maven2sbt/core/Gens.scala
- core/src/test/scala/maven2sbt/core/PropsSpec.scala
Added: `stringsMkString` to replace `mkString` to make sure `Seq[A]` is `Seq[String]` when `mkString`
> Added: stringsMkString to replace mkString to make sure Seq[A] is Seq[String] when mkString

- changelogs/1.1.0.md
- project/SbtProjectInfo.scala
* Add props name param (`--props-name`) (#167)
* Fix - possible reserved sbt words used as property names (e.g. `scalaVersion`, `version`, etc.) (#147)
* Fixed missing id and name handling for a repository (#148)
* Fix - Handle properties in properties, dependencies and repositories properly (#149)
* `ExclusionRule` is set with the incorrect named parameter (#158)
* String interpolation is broken (#168)
* Some `String` values are not rendered with props properly (#170)
> maven2sbt v1.1.0

- core/src/main/scala/maven2sbt/core/BuildSbt.scala
- core/src/main/scala/maven2sbt/core/ProjectInfo.scala
- core/src/test/scala/maven2sbt/core/ProjectInfoSpec.scala
Close #197 - Support getting `groupId` from `<parent>` element if no `groupId` is found in `pom.xml`
> Close #197 - Support getting groupId from <parent> element if no groupId is found in pom.xml

- .scripts/install.sh
- changelogs/1.2.0.md
- project/SbtProjectInfo.scala
* Add support Maven's `<dependencyManagement>` (#185)
* Support Scala dependency with `scalaBinaryVersion` (#187)
* Use `libs` for `libraryDependencies` when it's found in `libs` (#190)
* Add `libs` name param (`--libs-name`) (#191)
* Add Scala binary version param (`--scala-binary-version-name` | `-b`) (#192)
* Support getting `groupId` from `<parent>` element if no `groupId` is found in `pom.xml` (#197)
> maven2sbt v1.2.0

- .github/workflows/manual-maven-sync.yml
Fixed: The param name for `project-version`
> Fixed: The param name for project-version

- .scripts/install-graal-ubuntu.sh
Updated: The installation script for Ubuntu to change the installation location from `/usr/local` to `$USER`
> Updated: The installation script for Ubuntu to change the installation location from /usr/local to $USER

- .scripts/install-graal-ubuntu.sh
Updated: The installation script for Ubuntu to change the installation location from `/usr/local` to `$HOME`
> Updated: The installation script for Ubuntu to change the installation location from `/usr/local` to `$HOME`

- cli/src/main/scala/maven2sbt/cli/MainIo.scala
Close #238 - Increase the column length of help descriptions from `80` to `100`
> Close #238 - Increase the column length of help descriptions from 80 to 100

- changelogs/1.3.0.md
- project/SbtProjectInfo.scala
* Support Scala `3.0.0-RC1` (#208)
* Build with GraalVM (#214)
* Release GraalVM Native Image for macOS and Linux (#218)
* Add installation script for GraalVM Native Image for macOS (#223)
* Add installation script for GraalVM Native Image for Ubuntu and Debian Linux (#225)
* Change GitHub Actions for better GraalVM support (#227)
* Add GraalVM Native Image build for Windows (#229)
* Increase the column length of help descriptions from `80` to `100` (#238)
* Stop uploading the jar files, the Debian package and the tarball file to GitHub Release (#240)
> maven2sbt v1.3.0

- website/package-lock.json
- website/package.json
Upgraded: Docusaurus
Should have kept `"prism-react-renderer": "~1.1.1"` since `1.2.0` is not working well with `additionalLanguages` setting.
> Upgraded: Docusaurus

- core/src/test/scala/maven2sbt/core/TestUtils.scala
Fixed: `TestUtils.findRange` - missing the last range
Added: The doc comment to findRange
> Fixed: TestUtils.findRange - missing the last range

- changelogs/1.4.0.md
* Support Scala `3.0.0` (#262)
* Publish directly to Maven Central (#254)
* ~~Support Scala `3.0.0-RC2` and Scala `3.0.0-RC3`~~ (#249)
> maven2sbt v1.4.0

- .github/workflows/build-graal.yml
- .github/workflows/build.yml
- .github/workflows/release.yml
- .scalafmt.conf
- build.sbt
- modules/maven2sbt-cli/src/main/scala/maven2sbt/cli/MainIo.scala
- modules/maven2sbt-cli/src/main/scala/maven2sbt/cli/Maven2SbtApp.scala
- modules/maven2sbt-cli/src/main/scala/maven2sbt/cli/Maven2SbtArgsParser.scala
- modules/maven2sbt-core/src/main/scala/maven2sbt/core/Maven2SbtError.scala
Bump Scala and libraries
- scala 3.1.2 => 3.2.1
- cats 2.8.0 => 2.9.0
- cats-effect 2.5.5 => 3.4.3
- hedgehog 0.9.0 => 0.10.1
- effectie 2.0.0-beta2 => 2.0.0-beta4
- logger-f 2.0.0-beta2 => 2.0.0-beta4
- pirate 4e8177ec1548780cbf62b0352e58bceb7a99bfd6 => 7797fb3884bdfdda7751d8f75accf622b30a53ed
- extras 0.20.0 => 0.26.0
- scalafmt 3.5.1 => 3.6.1
> Bump Scala and libraries

- build.sbt
Close #318 - Upgrade cats-effect to `3.4.4`
- cats-effect `3.4.4` fixes a memory leak in Deferred
> Close #318 - Upgrade cats-effect to 3.4.4

- modules/maven2sbt-core/src/main/scala/maven2sbt/core/MavenPropertyPlus.scala
- modules/maven2sbt-core/src/test/scala/maven2sbt/core/MavenPropertySpec.scala
Fix #330 - Property should not take `#REM` from Maven properties
> Fix #330 - Property should not take `#REM` from Maven properties

- build.sbt
- modules/maven2sbt-cli/src/main/scala/maven2sbt/cli/MainIo.scala
Close #334 - Upgrade libraries: cats-effect, effectie, logger-f and extras
* cats-effect to 3.4.8
* effectie to 2.0.0-beta9
* logger-f to 2.0.0-beta12
* extras to 0.38.0
> Close #334 - Upgrade libraries: cats-effect, effectie, logger-f and extras

- build.sbt
- project/build.properties
Bump sbt to `1.9.1` and update `build.sbt` - remove `testFrameworks` setup for hedgehog as it's now one of the supported default test frameworks
> Bump sbt to 1.9.1 and update build.sbt - remove testFrameworks setup for hedgehog as it's now one of the supported default test frameworks

- modules/maven2sbt-core/src/main/scala/maven2sbt/core/DependencyPlus.scala
- modules/maven2sbt-core/src/main/scala/maven2sbt/core/LibsPlus.scala
- modules/maven2sbt-core/src/main/scala/maven2sbt/core/Scope.scala
- modules/maven2sbt-core/src/test/scala/maven2sbt/core/DependencySpec.scala
- modules/maven2sbt-core/src/test/scala/maven2sbt/core/LibsSpec.scala
- modules/maven2sbt-core/src/test/scala/maven2sbt/core/ScopeSpec.scala
Fix #339 - Update Scope handling including scope from props
Refactored Scope parsing and rendering methods to better handle unknown scopes. The methods now return a Scope object with an Unknown type instead of an error when an unrecognised scope is encountered. When the unknown scope is using props, it can be handled properly with this change.
> Fix #339 - Update Scope handling including scope from props

- changelogs/1.5.0.md
* Fix: Issue with Unsupported scope (#339)
* Exclude should not have Scala binary version suffix (#327)
The old exclusions look like
```scala
exclude("group-id", "artifact-id_${props.scalaBinaryVersion}")
```
```scala
excludeAll(
ExclusionRule(organization = "group-id", name = "artifact-id_${props.scalaBinaryVersion}"),
ExclusionRule(organization = "group-id2", name = "artifact-id2"),
)
```
It is now done like these instead.
```scala
excludeAll("group-id" %% "artifact-id")
```
```scala
excludeAll(
"group-id" %% "artifact-id",
"group-id2" % "artifact-id2",
)
```
It is much cleaner this way.
* Make `GlobalSettings.empty` constant (#285)
Make `GlobalSettings.empty` constant.
`GlobalSettings.empty` is currently `def` so it creates a new instance of an empty `GlobalSettings` whenever …
> maven2sbt v1.5.0

- .scripts/install-graal-macos.sh
- .scripts/install-graal-ubuntu.sh
- .scripts/install.sh
Update default version to 1.5.0 and URL in installation scripts
This commit modifies the .scripts/install-graal-ubuntu.sh, .scripts/install.sh, and .scripts/install-graal-macos.sh files. It updates the default app version from 1.4.0 to 1.5.0 and corrects the case of the username in the download URL. This is done to reflect the release of maven2sbt-cli version 1.5.0 and handle a possible case sensitivity issue that could prevent successful downloading of the package. [skip ci]
> Update default version to 1.5.0 and URL in installation scripts

- build.sbt
Update cats-effect, effectie and logger-f versions
- cats-effect: 3.4.10 => 3.5.1
- effectie: 2.0.0-beta9 => 2.0.0-beta10
- logger-f: 2.0.0-beta12 => 2.0.0-beta15
> Update cats-effect, effectie and logger-f versions

- build.sbt
- modules/maven2sbt-cli/src/main/scala/maven2sbt/cli/MainIo.scala
- modules/maven2sbt-cli/src/main/scala/maven2sbt/cli/Maven2SbtArgs.scala
- modules/maven2sbt-cli/src/main/scala/maven2sbt/cli/Maven2SbtArgsParser.scala
- modules/maven2sbt-core/src/main/scala-2.12_2.13/maven2sbt/core/data.scala
- modules/maven2sbt-core/src/main/scala-3/maven2sbt/core/data.scala
- modules/maven2sbt-core/src/main/scala/maven2sbt/core/BuildSbt.scala
- modules/maven2sbt-core/src/main/scala/maven2sbt/core/Dependency.scala
- modules/maven2sbt-core/src/main/scala/maven2sbt/core/DependencyPlus.scala
- modules/maven2sbt-core/src/main/scala/maven2sbt/core/Exclusion.scala
- modules/maven2sbt-core/src/main/scala/maven2sbt/core/LibsPlus.scala
- modules/maven2sbt-core/src/main/scala/maven2sbt/core/Maven2Sbt.scala
- modules/maven2sbt-core/src/main/scala/maven2sbt/core/ProjectInfo.scala
- modules/maven2sbt-core/src/main/scala/maven2sbt/core/Prop.scala
- modules/maven2sbt-core/src/main/scala/maven2sbt/core/PropsPlus.scala
- modules/maven2sbt-core/src/main/scala/maven2sbt/core/RepositoryPlus.scala
- modules/maven2sbt-core/src/main/scala/maven2sbt/core/Scope.scala
- modules/maven2sbt-core/src/test/scala/maven2sbt/core/BuildSbtSpec.scala
- modules/maven2sbt-core/src/test/scala/maven2sbt/core/DependencySpec.scala
- modules/maven2sbt-core/src/test/scala/maven2sbt/core/ExclusionSpec.scala
- modules/maven2sbt-core/src/test/scala/maven2sbt/core/Gens.scala
- modules/maven2sbt-core/src/test/scala/maven2sbt/core/LibsSpec.scala
- modules/maven2sbt-core/src/test/scala/maven2sbt/core/ProjectInfoSpec.scala
- modules/maven2sbt-core/src/test/scala/maven2sbt/core/PropSpec.scala
- modules/maven2sbt-core/src/test/scala/maven2sbt/core/PropsSpec.scala
- project/plugins.sbt
Close #349 - Upgrade libraries and sbt plugins
* cats-effect to `3.5.2`
* effectie to `2.0.0-beta13`
* logger-f to `2.0.0-beta23`
* extras to `0.44.0`
* pirate to `faff703b67fd10199098e806a3f6858982823461`
* sbt-devoops to `3.0.0`
* sbt-docusaur to `0.15.0`
* sbt-tpolecat to `0.5.0`
Update the broken code in accordance with the new versions of the libraries
> Close #349 - Upgrade libraries and sbt plugins

- build.sbt
Close #352 - Add refined4s as a dependency library for Scala 3
> Close #352 - Add refined4s as a dependency library for Scala 3

- .github/workflows/release.yml
- build.sbt
- project/build.properties
- project/plugins.sbt
Upgrade sbt to 1.11.0 and the sbt-ci-release plugin to 1.11.0 / clean up unused build settings related to the old Maven Central (OSSRH)
Due to the end-of-life (sunset) of OSSRH, upgrading sbt to 1.11.0 and sbt-ci-release to 1.11.0 was required in order to publish artifacts to the Central Publisher Portal (Maven Central).
> Upgrade sbt to 1.11.0 and the sbt-ci-release plugin to 1.11.0 / clean up unused build settings related to the old Maven Central (OSSRH)
